### ISSUE TITLE
Missing Feature: need to hide navigation bar or set its background color for the Activity/UIViewController 

### ISSUE THREAD

**Issue by jamesatgithub** [Clancey/SimpleAuth#11]
to match the UI style of app, the navigation bar needs customization support e.g. hide/show or background color

**Comment by Clancey** [comment]
You actually have full control over this already. Using UIAppearance you can tweak it on iOS. 

If you need more control as the readme says, you can set your own presenter. Here is the code where I setup the built in ones. But you can easily subclass them, style them and then plug them in.

https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthApi.cs#L33-L77

**Comment by jamesatgithub** [comment]
Thanks for the quick update. I'm using SimpleAuth in a PCL based Xamarin.Forms app, it would be better to make it easier for activity/UIViewController customization as most cases just need the navigation bar same color as the app's other screen, nothing else

**Comment by jamesatgithub** [comment]
hmm was trying to make a custom page renderer for the WebAuthenticatorViewController but found render cannot inherit this as it needs to inherit from PageRenderer... it would need much work for a simple customization of the navigation bar color... it would be great that there is another parameter which can be passed in the activity/UIViewController like the tittle does now

**Comment by Clancey** [comment]
There is no need for a custom renderer.   If this was for forms only, it would be easy to give you something like a color to pass on. But since this is for native and forms thats easier said than done.

You would need to customize in the iOS/Android side.  On iOS, just copy this code https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthApi.cs#L34-L52

To your app Delegate. Then you can modify the UINavigationController. 

On android you will need to subclass the WebAuthenticatorActivity, and then do the same thing for android. Add your own presenting code. And you can again borrow it from the OAuthApi.cs

Since it's so easy to jump in and do this on the native side I will not be adding support for theming the controls. Theming is huge and outside the scope of this project. If you ever need something custom you can always just inject your own custom Authenticator. You could even go as far as creating a Forms version of the WebAuthenticatorViewController

**Comment by jamesatgithub** [comment]
I got your idea, the reason I was trying to make a render because our app has two types of users and each type has its own theming (blue navigation bar and green navigation bar), I need to pass the user type (color) dynamically from the Core view model (PCL).

**Comment by Clancey** [comment]
Simple. Set a global style color in your PCL that is forms. Then on the native side http://stackoverflow.com/questions/25175477/convert-xamarin-forms-color-to-platform-specific-color




On Thu, Aug 11, 2016 at 6:09 PM -0800, "jamesatgithub" <notifications@github.com<mailto:notifications@github.com>> wrote:


I got your idea, the reason I was trying to make a render because our app has two types of users and each type has its own theming (blue navigation bar and green navigation bar), I need to pass the user type (color) dynamically from the Core view model (PCL).

-

**Comment by jamesatgithub** [comment]
Thanks I can get the color based on app settings - this is OK.
Just tried the below code in AppDelegate but ShowAutenticator custom action isn't been triggered, what could be the reason? 

`SimpleAuth.OAuthApi.ShowAuthenticator = (authenticator) =>
            {
                var invoker = new Foundation.NSObject();
                invoker.BeginInvokeOnMainThread(() =>
                {
                    //color comes from settings
                    var vc = new ThemedWebAuthenticatorViewController(color,authenticator);
                    var window = UIKit.UIApplication.SharedApplication.KeyWindow;
                    var root = window.RootViewController;
                    if (root != null)
                    {
                        var current = root;
                        while (current.PresentedViewController != null)
                        {
                            current = current.PresentedViewController;
                        }
                        current.PresentViewControllerAsync(new UIKit.UINavigationController(vc), true);
                    }
                });
            };`

**Comment by jamesatgithub** [comment]
OK I reviewed source and found the solution:
I don't want to subclass all the provider apis so what I did is:
1. make a injection service to set the static custom action of OAuthApi.ShowAuthenticator for Core pcl
2. in my pcl, after constructor call of GoogleAPI/TwitterAPI/FacebookAPI class, call above injection service to overwrite the OAuthApi constructor initialization to use custom ViewController/Activity

**Comment by jamesatgithub** [comment]
above solution works with iOS, but for android:
https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthApi.cs#L54-L66
the State and StateRepo are all internal ones and I cannot use above code it in my subclass of WebAuthenticatorActivity. any suggestion or fix?

**Comment by Clancey** [comment]
Want to make that stuff public or protected and send me a pull request?

--
Clancey

**Comment by jamesatgithub** [comment]
pull request sent. Thanks
