### ISSUE TITLE
Example how to use libray with own server

### ISSUE THREAD

**Issue by Nyrris** [Clancey/SimpleAuth#14]
Do you have an example or documentation how this library can be used for authenticating with Oauth2 by own server (which doesn't have a web login) ?

**Comment by Clancey** [comment]
Yes use https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthPasswordApi.cs

However as you can see the auto showing of the UI only works for iOS. 

https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthPasswordApi.cs#L21-L32

This is because you really should show your own pretty custom login!  Or feel free to implement a generic username/password popup for Android and send a pull request!

**Comment by Nyrris** [comment]
Thanks for your fast response, I did look at the code and could not find where I can add the user credentials in the request. I did now have:

			LoginButton.Clicked += async (object sender, EventArgs e) =>
			{
				var api = new OAuthPasswordApi(
					"login",
					App.ClientId,
					App.ClientSecret,
					App.RedirectUrl,
					App.AccessTokenUrl,
					App.AuthorizeUrl
				);

				var account = await api.Authenticate();
}

When I do run this code, a system.BadImageFromatExceprion is throwed. could you give me some directions how to implement?

**Comment by Clancey** [comment]
A few things, is this done inside a PCL?

You need to make sure you add SimpleAuth to the client apps as well, not just the PCL.

Also you should keep the scope of the API outside the button press. You will keep using this API everywhere.

https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Forms/Sample.Forms/App.cs#L40

See how they button just calls Authenticate?

As for the null exception, you are most likely hitting the UserName prompt I mentioned before.  I updated the Xamarin.Forms sample to show how to use your own custom login page.
https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Forms/Sample.Forms/App.cs#L42-L44

**Comment by Clancey** [comment]
Is this during login or after login? Typically client_id is a query param not in the header during the post.  You may have to create your own authenticator/ subclass OAuthApi. You could always just add the default header to the build in Api.Client inside the constructor.  It just depends on when/where you are getting this issue.  It's sad how differently most thing implement OAuth.

**Comment by Nyrris** [comment]
I got this error while logging in, my back end system is a symfony2 web application which has already implemented OAuth by using fos restBundle. I will try to add the default header to the Api tomorrow, let you know if I got it to work.

**Comment by Clancey** [comment]
It could be you need the clientID header when posting token data.  Amazon requried redirect_url, so this is how its handled:
https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/Providers/Amazon.cs#L36

**Comment by Nyrris** [comment]
Then I will look at the documentation of the bundle used by the back end, maybe it is explained there when the bundle expects the client id.

**Comment by Nyrris** [comment]
After some research in the back end, i noticed that the client id and secret are expected to be in the post parameters. So I did implement my own authenticator and api like you suggested and now it works fine. Thanks for your help.

I still have some few questions, how can I log out a user and redirect it to the login page? 
And on the login page I have a button which redirects to an information page, but with the new implementation of the login this doens't work anymore.

Button.Clicked += async (object sender, EventArgs e) =>
			{
				await App.Navigation.PushAsync(new TourPage());
			};

**Comment by Nyrris** [comment]
Found the logout method. Only the question left why the page load isn't working.

**Comment by Clancey** [comment]
You are having issues with forms. It's a little outside the scope of this project.  Make sure that the show authenticator is being called. https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Forms/Sample.Forms/App.cs#L21 
So put a break point on MainPage.Navigation.PushModalAsync (new LoginPage (obj));  
IF so the issue is in there, where you might be pushing a model, and you already have something else on top. You can always check the Navigations, ModalStack and Navigation Stack to get the top page and present the modal from there.
