### ISSUE TITLE
SimpleAuth for Winforms

### ISSUE THREAD

**Issue by TomQv** [Clancey/SimpleAuth#52]
I'm trying to add a class to use SimpleAuth also in WinForm-apps. Actually not so difficult. Just a new class-library with a Login-Form with a WebBrowser-control and a implementation of IAuthStorage.
It works fine, but I only have one small problem.

How to change user for OneDrive?

I can change user for DropBox just by deleting the stored account in IAuthStorage. Then DropBox is showing the login-window on next time.
But for OneDrive this doesn't work with my Forms.WebBrowser implementation. I'm still logged in. The url-call from authenticator.GetInitialUrl() is immediately answered with a valid code.

Maybe something with cookies? Any ideas?

Tom

**Comment by Clancey** [comment]
Using .net standard 2.0 you shouldn't need to implement the iAuthStorage it ships one: https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth.Net/AuthStorage.cs .   It's hard to say where your bug is. But by default, everything should stay separate, You can look at the other native implementations too see how it should work.

**Comment by TomQv** [comment]
The trick is, to set WebBrowser not to save cookies with INTERNET_SUPPRESS_COOKIE_PERSIST:
https://stackoverflow.com/questions/912741/how-to-delete-cookies-from-windows-form
