### ISSUE TITLE
Sample.Mac Doesn't work on 10.11 and 10.12

### ISSUE THREAD

**Issue by allan-chin** [Clancey/SimpleAuth#94]
On 10.11 and 10.12, the RedirectUri is not received in the AppDelegate.OpenUrls() method. No problem on 10.13 and 10.14. Can this be fixed, or is there another way I can get the Authorization Code in a Xamarin.Mac app. Thanks.

**Comment by Clancey** [comment]
It doesn't work with the CFBundleURLTypes in the info.plist? https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Mac/Info.plist#L31-L41

**Comment by allan-chin** [comment]
Correct. I run the same project with the same info.plist on 10.13 and 10.14 and the redirect comes in.

**Comment by Clancey** [comment]
That is a little strange. There are a few things you could do to work around it. One is use the WebAuthenticator on the older versions, instead of the Native Authenticator. 

Something else you can try is here: https://developer.apple.com/library/archive/documentation/Carbon/Conceptual/LaunchServicesConcepts/LSCConcepts/LSCConcepts.html

Under Application Registration, you can manually register your app for those url scheme.

**Comment by allan-chin** [comment]
For 10.11 and 10.12, I used this mechanism to get the RedirectURL.

    public AppDelegate()
    {
        // https://forums.xamarin.com/discussion/118220/app-launch-via-custom-url-scheme
        var appleEventManager = NSAppleEventManager.SharedAppleEventManager;
        appleEventManager.SetEventHandler(this, new ObjCRuntime.Selector("handleGetURLEvent:withReplyEvent:"), AEEventClass.Internet, AEEventID.GetUrl);
    }

    [Export("handleGetURLEvent:withReplyEvent:")]
    private void HandleGetURLEvent(NSAppleEventDescriptor evt, NSAppleEventDescriptor replyEvent)
    {
        // Received event is a list (1-based) of URL strings
        for (int i = 1; i <= evt.NumberOfItems; i++)
        {
            var innerDesc = evt.DescriptorAtIndex(i);

            if (!string.IsNullOrEmpty(innerDesc.StringValue))
            {
                Console.WriteLine("Get URL: " + innerDesc.StringValue);
            }
        }
    }
