### ISSUE TITLE
Need Proper Documentation

### ISSUE THREAD

**Issue by onlinecheckwriter** [Clancey/SimpleAuth#97]
Hello,
Could you please write a proper documentation please or video how to add it for Sign it with google.

**Comment by Clancey** [comment]
The [readme](https://github.com/Clancey/SimpleAuth/blob/master/README.md) is pretty comprehensive, there are also [samples](https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.iOS/AppDelegate.cs ).  Since this is an open source project, I welcome pull requests adding more documentation.
